import aqCase from "../img/aquacacerola24cm.jpg"


const productos = [
    {
      id: 1,
      categoria: "cacerolas",
      nombre: "cacerola cuadrada 29",
      precio: 13000,
      foto: {aqCase},
      stock: 10,
    },
    {
      id: 2,
      categoria: "cacerolas",
      nombre: "cacerola cuadrada 24",
      precio: 13000,
      foto: "../img/aquacacerola24cm.jpg",
      stock: 10,
    },
    {
      id: 3,
      categoria: "cacerolas",
      nombre: "cacerola 20",
      precio: 13000,
      foto: "../img/Cacerola Aqua 20cm.jpg",
      stock: 10,
    },
    {
      id: 4,
      categoria: "cacerolas",
      nombre: "cacerola 24",
      precio: 13000,
      foto: "../aquacacerola24cm.jpg",
      stock: 10,
    },
    {
      id: 5,
      categoria: "cacerolas",
      nombre: "cacerola 28",
      precio: 13000,
      foto: "../Cacerola 28 Aqua.jpg",
      stock: 10,
    },
    {
      id: 6,
      categoria: "cacerolas",
      nombre: "cacerola 18 con mango",
      precio: 13000,
      foto: "../img/aquacacerolaconmango18cm.jpg",
      stock: 10,
    },
    {
      id: 7,
      categoria: "sartenes",
      nombre: "sarten 18",
      precio: 13000,
      foto: "../img/Sarten18Aquacontapadevidrio.jpg",
      stock: 10,
    },
    {
      id: 8,
      categoria: "sartenes",
      nombre: "sarten 24",
      precio: 13000,
      foto: "../img/aquasarten24cm.jpg",
      stock: 10,
    },
    {
      id: 9,
      categoria: "sartenes",
      nombre: "sarten 31 con asas",
      precio: 13000,
      foto: "../img/sartenconasas31cm.jpg",
      stock: 10,
    },
    {
      id: 10,
      categoria: "sartenes",
      nombre: "sarten 20",
      precio: 13000,
      foto: "../img/Sartén aqua 20cm.jpg",
      stock: 10,
    },
    {
      id: 11,
      categoria: "sartenes",
      nombre: "sarten 28",
      precio: 13000,
      foto: "../img/Sarten 28 Aqua.jpg",
      stock: 10,
    },
    {
      id: 12,
      categoria: "sartenes",
      nombre: "sarten chef sensor",
      precio: 13000,
      foto: "../img/chefsarten.jpg",
      stock: 10,
    },
    {
      id: 13,
      categoria: "sartenes",
      nombre: "wok sensor",
      precio: 13000,
      foto: "../img/chefwok.jpg",
      stock: 10,
    },
    {
      id: 14,
      categoria: "fuentes",
      nombre: "fuente rectangular 30",
      precio: 13000,
      foto: "../img/FuenteRectangular30 Aqua.jpg",
      stock: 10,
    },
    {
      id: 15,
      categoria: "biferas",
      nombre: "bifera con asas",
      precio: 13000,
      foto: "../img/aquabiferaconasascm.jpg",
      stock: 10,
    },
    { id: 16, 
      categoria: "flip", 
      nombre: "flip", 
      precio: 13000, 
      foto: "../img/aquaflip.jpg",
      stock: 10, 
    },
    {
      id: 17,
      categoria: "complementos",
      nombre: "budineras terra x2",
      precio: 13000,
      foto: "../img/setdebudineras2.jpg",
      stock: 10,
    },
    {
      id: 18,
      categoria: "complementos",
      nombre: "savarin 18 terra",
      precio: 13000,
      foto: "../img/Savarin 18 rosa.jpg",
      stock: 10,
    },
    {
      id: 19,
      categoria: "complementos",
      nombre: "savarin 24 terra",
      precio: 13000,
      foto: "../img/terrasavarin24cm2.jpg",
      stock: 10,
    },
    {
      id: 20,
      categoria: "complementos",
      nombre: "savarin 28 terra",
      precio: 13000,
      foto: "../img/terrasavarin28cm2.jpg",
      stock: 10,
    },
    {
      id: 21,
      categoria: "complementos",
      nombre: "cestillo freidor",
      precio: 13000,
      foto: "../img/freidorparacacerola.jpg",
      stock: 10,
    },
    {
      id: 22,
      categoria: "complementos",
      nombre: "vaporizador con tapa",
      precio: 13000,
      foto: "../img/vaporizadorcontapa.jpg",
      stock: 10,
    },
    {
      id: 23,
      categoria: "complementos",
      nombre: "savarin 24 terra",
      precio: 13000,
      foto: "../img/terrasavarin24cm2.jpg",
      stock: 10,
    },
  ];
  
 export const itemList = new Promise((resolve, reject) => {
    let condition = true;
    if (condition) {
      setTimeout(() => {
        resolve(productos);
      }, 2000);
    } else {
      reject("400 - not found");
    }
  });